spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8888
jwt:
  secret: "secretTestSecretTestSecretTestSecretTestSecretTest"
  expiration-time: 866000000